### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by mycroes** [gisellevonbingen/Giselle.Net.EtherNetIP#1]
This repository does not include license information. Would you be willing to add a license to clarify the allowed use? If you're in doubt what license to use, I would personally favor MIT because that also allows companies to use this code with modifications without requiring those companies to contribute those modifications back. I'm also using that for [mycroes/Sally7](/mycroes/Sally7). However, IANAL, feel free to choose otherwise.

**Comment by gisellevonbingen** [comment]
thx for your interest
license added as MIT (b9cb4fbdd7abb8ea8d224fb4a113008df18ebe25 426fe63982ecef7be8898a94376b47549afc7087)
hope this helps

**Comment by mycroes** [comment]
Thanks! We're currently using [EEIP.NET](/rossmann-engineering/EEIP.NET) at a customer to communicate with some Fanuc and Staubli devices, but we couldn't perform implicit communication with multiple devices because either the devices don't support implicit connections to UDP ports other than 2222 or the library doesn't communicate the alternate port. Other than that I wasn't very happy with the code in EEIP.NET, your code seems to be a lot cleaner though.

We're gonna give your library a try and see if it makes any difference with regards to the implicit communication. If it doesn't change the problem (i.e. bound to port 2222 for multiple implicit connections) we'll see where we'll go from there.
