### ISSUE TITLE
Configuration assembly

### ISSUE THREAD

**Issue by kenghuaku** [gisellevonbingen/Giselle.Net.EtherNetIP#5]
GiselleEIPLib seems to lack the definitions for Configuration assembly(ConfigurationAssemblyInstanceID, ConfigurationSize and ConfigurationData). Some scanners place the initial settings in the Configuration (during the first Forward Open)

**Comment by gisellevonbingen** [comment]
Unfortunately my device looks not use Configuration assembly.
Maybe some code marked as reserved is it.
https://github.com/gisellevonbingen/Giselle.Net.EtherNetIP/blob/d057214d0c80dd413404d68f341f3336ae3da145/Giselle.Net.EtherNetIP/CIP/CIPCodec.cs#L79-L82

I'll try the test again, but currently there is no way for me to implement it.

**Comment by gisellevonbingen** [comment]
Transferred to #6
